
import { Language, TranslationStrings } from './types';

export const TRANSLATIONS: Record<Language, TranslationStrings> = {
  [Language.EN]: {
    appName: "Mida Pro",
    encrypt: "Encryption",
    decrypt: "Decryption",
    settings: "Settings",
    carrierImage: "Carrier Image",
    secretFile: "Secret File",
    password: "Password",
    passwordHint: "Min 8 chars: 1 Upper, 1 Lower, 1 Number",
    process: "Process",
    selectImage: "Select Image",
    selectFile: "Select File",
    language: "Language",
    theme: "Theme",
    errorInvalidPassword: "Password must be at least 8 characters with 1 uppercase, 1 lowercase, and 1 digit.",
    errorNoImage: "Please select a carrier image.",
    errorNoFile: "Please select a secret file.",
    success: "Operation successful!",
    download: "Download Result",
    back: "Back",
    aboutUs: "Mida Huk Universe",
    finish: "Finish",
    midaHukTitle: "Mida Huk Group",
    midaHukDescription: "The ultimate digital fortress and innovation hub. We don't just follow trends; we define the future of technology and security.",
    trainingTitle: "Mida Academy",
    trainingDesc: "Elite training programs across Cybersecurity, AI, Web3, and Software Engineering. From zero to professional mastery.",
    expertiseTitle: "Cyber Intelligence",
    expertiseDesc: "Advanced penetration testing, incident response, and cryptographic solutions for the modern world.",
    innovationTitle: "Dev & Growth",
    innovationDesc: "High-performance software development and strategic technical consulting for global enterprises."
  },
  [Language.AR]: {
    appName: "ميدأ برو",
    encrypt: "تشفير",
    decrypt: "فك التشفير",
    settings: "الإعدادات",
    carrierImage: "صورة الحامل",
    secretFile: "الملف السري",
    password: "كلمة المرور",
    passwordHint: "٨ أحرف على الأقل: حرف كبير، صغير، ورقم",
    process: "معالجة",
    selectImage: "اختر صورة",
    selectFile: "اختر ملفاً",
    language: "اللغة",
    theme: "المظهر",
    errorInvalidPassword: "يجب أن تكون كلمة المرور ٨ أحرف على الأقل، وتحتوي على حرف كبير وصغير ورقم.",
    errorNoImage: "يرجى اختيار صورة الحامل.",
    errorNoFile: "يرجى اختيار الملف السري.",
    success: "تمت العملية بنجاح!",
    download: "تحميل النتيجة",
    back: "رجوع",
    aboutUs: "عالم ميدأ هوك",
    finish: "إنهاء",
    midaHukTitle: "مجموعة Mida Huk",
    midaHukDescription: "الحصن الرقمي النهائي ومركز الابتكار. نحن لا نتبع التطور بل نصنعه في مجالات التكنولوجيا والأمن.",
    trainingTitle: "أكاديمية ميدأ",
    trainingDesc: "برامج تدريبية للنخبة في الأمن السيبراني، الذكاء الاصطناعي، وهندسة البرمجيات. من الصفر إلى الاحتراف.",
    expertiseTitle: "الاستخبارات السيبرانية",
    expertiseDesc: "اختبار اختراق متقدم، استجابة للحوادث، وحلول تشفير مصممة للعالم الحديث.",
    innovationTitle: "التطوير والنمو",
    innovationDesc: "تطوير برمجيات عالية الأداء واستشارات تقنية استراتيجية للمؤسسات العالمية."
  }
};
